sudo: required
group: deprecated-2017Q3
services:
- docker
language: node_js
node_js:
- 9.11.1
env:
  global:
  - CC_TEST_REPORTER_ID=f9a7cc51d41f847d9b5c91f469606222755355ec9ea001c6bd7a16d20f45941f
before_script:
- npm install coveralls
- docker-compose -f docker-compose.test.yml up -d
script:
- docker exec -it tropical-hazards-front npm test
after_script:
- "./node_modules/coveralls/bin/coveralls.js < ./test/unit/coverage/lcov.info"
- docker-compose down --remove-orphans
after_success:
- docker login --username=_ --password=$HEROKU_AUTHTOKEN registry.heroku.com
- docker build -f Dockerfile.prod -t deploy_image .
- |
  if [ "${TRAVIS_BRANCH}" == "development" ]; then 
    echo "Deploying to homolog environment..."  
    docker tag deploy_image registry.heroku.com/tropical-hazards-homolog/web
    docker push registry.heroku.com/tropical-hazards-homolog/web
  else if [ "${TRAVIS_BRANCH}" == "master" ]; then
    echo "Deploying to production environment..."
    docker tag deploy_image registry.heroku.com/tropical-hazards/web
    docker push registry.heroku.com/tropical-hazards/web
  else
    echo "Skipping deploy...";
  fi;
  fi;
